spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: EY2rvRn7KxhRTXi721wT
            client-secret: eCIf6ZsnMI
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/wordbox
    username: root
    password: thrmEkel123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: yrKE36QRt5aRNqtfTdTwhVijbIB0lNQDpPxcdoqdEPPyASnDHFrsHjkr4pcHKhKh